services:
  db:
    image: postgres:15-alpine
    container_name: vkahub-db-dev
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin-61kaf-vkahub}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin-61kaf-vkahub}
      POSTGRES_DB: ${POSTGRES_DB:-vkahub}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - vkahub-net

  api:
    build:
      context: ./server/backend
      dockerfile: Dockerfile
    container_name: vkahub-api-dev
    depends_on:
      - db
    env_file:
      - ./server/.env
    ports:
      - "5000:5000"
    volumes:
      - ./server/backend/reports:/app/reports
      - ./server/backend/certificates:/app/certificates
      - ./server/backend/team-images:/app/team-images
      - ./server/backend/user-avatars:/app/user-avatars
    restart: unless-stopped
    networks:
      - vkahub-net

  nginx:
    image: nginx:alpine
    container_name: vkahub-nginx-dev
    depends_on:
      - api
    ports:
      - "80:80"
    volumes:
      - ./nginx/default:/etc/nginx/conf.d/default.conf
      - ./server/backend/certificates:/certificates
      - ./server/backend/reports:/reports
      - ./server/backend/user-avatars:/user-avatars
      - ./server/backend/team-images:/team-images
    restart: unless-stopped
    networks:
      - vkahub-net

networks:
  vkahub-net:
    name: vkahub-net
    driver: bridge

volumes:
  db_data:
  pgadmin:
