database:
  username: postgres
  password: postgres
  host: database
  port: 5432
  databaseName: vkahub
  sslMode: false

migrations:
  enable: true
  connUri: postgres://postgres:postgres@database:5432/vkahub?sslmode=disable
  dirUrl: file:///app/migrations

authorizer:
  accessSecretKey: access-vkahub-secret-vkahub-key
  refreshSecretKey: refresh-vkahub-secret-vkahub-key

onliner:
  address: http://onliner:6379
  password: 
  databaseNum: 0

file-storage:
  address: file-storage:9000
  username: minio-root
  password: minio-root
  enableSSL: false
  initBucket: vkahub-bucket

broker:
  address:
  exchange:
  routingKey:
  queue: 
